# Nixpacks config for boundaries-training within monorepo context
# This tells Nixpacks to build from the workspace root even though
# Coolify points to this app directory

[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = [
  # Navigate to workspace root
  "cd ../..",
  # Enable pnpm
  "corepack enable",
  "corepack prepare pnpm@9.9.0 --activate",
  # Install all workspace dependencies from root
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  # Build from workspace root using Turborepo filter
  "cd ../..",
  "pnpm --filter boundaries-training build"
]

[start]
# Start from app directory
cmd = "cd ../../apps/boundaries-training && pnpm start"

[variables]
NODE_ENV = "production"
